name: Reusable check job

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - run: npm ci

      - run: npm run format:check
      - run: npm run lint --workspaces
      - run: npm run type-check --workspaces
      - run: npm run test:all
      - run: npm run build --workspaces --if-present
