name: Reusable check job

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'

      - run: npm ci

      - run: npm run format:check
      - run: npm run lint --workspaces
      - run: npm run type-check --workspaces
      - run: npm run test:all
      - run: npm run build --workspaces --if-present
